version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    working_dir: /app
    command: [ "/app/server" ]

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5440:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
